-- Rode este script no SQL Editor do Supabase antes do primeiro uso.
-- Para um app simples com acesso por link, deixe RLS desativado nessas tabelas.
-- Se quiser controle por login, ative RLS depois e crie policies específicas.

create table if not exists servidores (
  id bigint generated by default as identity primary key,
  nome text not null,
  ativo boolean not null default true,
  pode_doc boolean not null default true,
  pode_manha boolean not null default true,
  pode_tarde boolean not null default true,
  updated_at timestamp with time zone default now()
);

create table if not exists ausencias (
  id bigint generated by default as identity primary key,
  servidor text,
  data_inicio date,
  data_fim date,
  periodo text,
  tipo text,
  substituto_gil text,
  observacao text,
  updated_at timestamp with time zone default now()
);

create table if not exists feriados (
  id bigint generated by default as identity primary key,
  data date,
  descricao text,
  fonte text,
  updated_at timestamp with time zone default now()
);

-- Opcional: índices simples para deixar mais rápido.
create index if not exists idx_ausencias_servidor_datas on ausencias (servidor, data_inicio, data_fim);
create index if not exists idx_feriados_data on feriados (data);
